default_args: ["configs/_modular/sample_generation.yaml", "configs/_modular/model.yaml", "configs/_modular/grouping.yaml", "configs/_modular/dataset_test.yaml"]

############ modification of default args
model:
  spatial_shape: [500, 500, 1000]

############ non-default args
forest_path: 'data/benchmark/L1W_voxelized01_for_eval.laz'
pretrain: 'data/model_weights/epoch_675.pth'
fp16: True
tile_generation: True

dataloader:
  batch_size: 1
  num_workers: 2

shape_cfg:
  outer_remove: ~
  alpha: 0
  buffer_size_to_determine_edge_trees: 0.3

save_cfg:
  save_formats: ['laz']
  save_treewise: True
  save_pointwise: True
  return_type: 'original'
  results_dir: 'results_epoch675'
